name: Portfolio Tracker

on:
  workflow_dispatch:   # manually trigger workflow
  schedule:            # (optional) run every day at 6 AM
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python portfolio_tracker.py

      - name: Upload portfolio.xlsx as artifact
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-report
          path: portfolio.xlsx
