name: Portfolio Tracker

on:
  schedule:
    - cron: "30 12 * * *"   # Runs daily at 12:30 UTC (5:30 PM IST)
  workflow_dispatch:        # Lets you trigger manually from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python portfolio_tracker.py

      - name: Commit results
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add portfolio.xlsx
          git commit -m "Update portfolio data [skip ci]" || echo "No changes"
          git push
