name: Portfolio Tracker

on:
  schedule:
    # Runs every day at 12:30 UTC (6:00 PM IST)
    - cron: "30 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas openpyxl

      - name: Run portfolio script
        run: python portfolio_append.py

      - name: Commit updated portfolio-updates.xlsx
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add portfolio-updates.xlsx
          git commit -m "Update portfolio-updates.xlsx on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git pull --rebase origin main || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send weekly email with portfolio-updates.xlsx
        if: github.event.schedule == '30 12 * * 0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ vars.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Weekly Portfolio Update"
          to: ${{ vars.EMAIL_USER }}
          from: ${{ vars.EMAIL_USER }}
          body: "Attached is your weekly portfolio update."
          attachments: portfolio-updates.xlsx
